# Generated by Django 4.0.3 on 2022-09-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mbase', '0007_alter_imagealbum_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
